require "nana.options"
-- require "nana.keymaps"
-- require "nana.plugins"
-- require "nana.catppuccin"
-- require "nana.cmp"
-- require "nana.telescope"
-- require "nana.treesitter"
-- require "nana.autopairs"
-- require "nana.bufferline"
-- require "nana.comment"
-- require "nana.gitsigns"
-- require "nana.nvim-tree"
-- require "nana.lualine"
-- require "nana.toggleterm"

require "nana.autopairs"
require "nana.bufferline"
require "nana.catppuccin"
require "nana.cmp"
require "nana.comment"
require "nana.gitsigns"
require "nana.keymaps"
require "nana.lualine"
require "nana.nvim-tree"
require "nana.plugins"
require "nana.telescope"
require "nana.toggleterm"
require "nana.treesitter"

